---
title: "Levon_Gevorgyan_Homework_1"
output:
  pdf_document: default
  html_document: default
date: "2025-02-02"
---

```{r}
library(dplyr)
library(readr)
```

## Part 1

1. Load the dataset. Check the first 5 rows.

```{r}
df <- read_csv("/Users/levongevorgyan/Desktop/DataVisualization/crime_data.csv")
head(df, 5)
```

2. Identify columns with missing values and their respective counts. 
Drop columns where more than 50% of the data is missing (store this version as a 
new dataset).

```{r}
null_sum <- colSums(is.na(df))  
null <- missing_count[null_sum > 0]

print(missing_cols)
```
3. Convert the DATE OCC column to a datetime format. Extract the year, month, 
and day into separate columns. Create a new column for the hour using the 
TIME OCC column.

```{r}
df$DATE_OCC <- as.POSIXct(df$DATE_OCC, format="%m/%d/%Y %I:%M:%S %p")

df$year <- format(df$DATE_OCC, "%Y")
df$month <- format(df$DATE_OCC, "%m")
df$day <- format(df$DATE_OCC, "%d")

df$TIME_OCC <- as.POSIXct(df$TIME_OCC, format = "%H:%M:%S")

df$hour <- format(df$TIME_OCC, "%H")
```







